### ISSUE TITLE
Issue while trying to setup storybook using dynamic plugin sdk

### ISSUE THREAD

**Issue by AjayJagan** [openshift/dynamic-plugin-sdk#216]
We are using the dynamic plugin sdk to develop a self-provisioning ui for amq broker. In this, we are using storybook(https://storybook.js.org/) to ease the development of the UI. While trying to build the storybook components, the following error is seen

```
ERR! ModuleNotFoundError: Module not found: Error: Can't resolve '@console/dynamic-plugin-sdk/src/perspective/useActivePerspective' in '/Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/@openshift-console/dynamic-plugin-sdk/lib/api'
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/Compilation.js:2016:28
ERR!     at /Users/ajay/Work/KIE/activemq-artemis-self-provisioning-plugin/node_modules/webpack/lib/NormalModuleFactory.js:798:13
```

Any help is much appreciated! Thanks in advance

**Comment by ajaypratap003** [comment]
@vidyanambiar Can you please suggest the fix for this issue, this is kind of blocker for us.

**Comment by vidyanambiar** [comment]
@ajaypratap003 I transitioned to a different team a couple of months ago and haven't been working on the SDK.  
@florkbr @karelhala Could you provide input here please? Thank you!

**Comment by karelhala** [comment]
`useActivePerspective` hook has not been implemented in the dynamic plugin SDK yet. It looks like `@openshift-console/dynamic-plugin-sdk` is trying to import this non existing hook. @vojtechszocs any guidance on this?

**Comment by AjayJagan** [comment]
hi guys! any update on this :)

**Comment by ajaypratap003** [comment]
@vojtechszocs Can you please provide your guidance on this issue ? We would appreciate your guidance.
