### ISSUE TITLE
filter by annotation value i.e. in k8sListResource

### ISSUE THREAD

**Issue by shalberd** [openshift/dynamic-plugin-sdk#233]
@florkbr  Is is possible at all to filter by annotation instead of only label in k8sListResource?

In Openshift, default storage class is only marked and handled via an annotation, so getting the default one out of many is a pain currently without helper tools like jq or node-jq https://www.baeldung.com/linux/kubernetes-labels-annotations

Background: Red Hat Open Data Hub odh-dashboard is using this library here for interactions with the openshift API.

**Comment by christianvogt** [comment]
@shalberd Annotation based filtering must be applied client side as the k8s APIs only supports label filtering server side. For this reason I don't think it is a good idea for the SDK to support this. It, along with many other filters, can applied by the client on the result set returned by the SDK utility.

**Comment by shalberd** [comment]
Hi @christianvogt yes, I in the meantime have come to do that client-side, i.e. .filter 

`allStorageClasses.filter((storageclass) => storageclass.metadata.annotations?.['storageclass.kubernetes.io/is-default-class']?.includes('true'));`

Thank you for the quick feedback and reiteration of the concept, I appreciate it.
