### ISSUE TITLE
Modal dialog functions do not support generics

### ISSUE THREAD

**Issue by gnunn1** [openshift/dynamic-plugin-sdk#252]
The documentation for the new modal dialogs show them being called with generics however the dynamic SDK doesn't actually export them with generics as far as I can tell. For example the dynamic SDK reference page shows the following example for useLabelModels:

```
const PodLabelsButton = ({ pod }) => {
  const { t } = useTranslation();
  const launchLabelsModal = useLabelsModal<PodKind>(pod);
  return <button onClick={launchLabelsModal}>{t('Edit Pod Labels')}</button>
}
```
https://docs.openshift.com/container-platform/4.14/web_console/dynamic-plugin/dynamic-plugins-reference.html

Trying to call the function with a generic results in a compilation failure with the error:

```
TS2558: Expected 0 type arguments, but got 1.
```

The useDeleteModal does actually need to support generics since AFAIK it uses the type to determine whether non-cascading deletes are supported and shows a checkbox to enable this.

**Comment by rhamilto** [comment]
@florkbr, can you see this gets looked at?  Console has[ a downstream documentation bug](https://issues.redhat.com/browse/OCPBUGS-28585) as a result.

**Comment by rhamilto** [comment]
> @florkbr, can you see this gets looked at? Console has[ a downstream documentation bug](https://issues.redhat.com/browse/OCPBUGS-28585) as a result.

Scratch that.  This is a bug in https://github.com/openshift/console/tree/master/frontend/packages/console-dynamic-plugin-sdk, not https://github.com/openshift/dynamic-plugin-sdk

**Comment by gnunn1** [comment]
Closed as this was addressed, problem turns out to be a bug in the deletion dialog with Models that don't have a propagationPOlicy set. Issue opened in Red Hat issues for this.
